version: "2"

services:
  inservice:
    mem_limit: 75m
    restart: on-failure
    image: ingvarjackal/tgstickers-inservice
    ports:
      - 10000:10000
    environment:
     - REDIS_URI=redis://redis:6379
     - JAVAMEM=70m
     - LOG4JCONF=log4jprod.xml
     - SENTRY_DSN=$SENTRY_DSN
     - SENTRY_SERVERNAME=$HOSTNAME
     - COMMANDS=dockerize -wait tcp://redis:6379
     - BOT_TOKEN=$BOT_TOKEN
     - LOGGING_LEVEL=INFO
    depends_on:
      - redis
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "5"

  outservice:
    mem_limit: 75m
    restart: on-failure
    image: ingvarjackal/tgstickers-outservice
    ports:
      - 10002:10000
    environment:
      - REDIS_URI=redis://redis:6379
      - COMMANDS=dockerize -wait tcp://redis:6379
      - JAVAMEM=70m
      - LOG4JCONF=log4jprod.xml
      - SENTRY_DSN=$SENTRY_DSN
      - SENTRY_SERVERNAME=$HOSTNAME
      - BOT_TOKEN=$BOT_TOKEN
      - LOGGING_LEVEL=INFO
    depends_on:
      - redis
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "5"

  blservice:
    mem_limit: 90m
    restart: on-failure
    image: ingvarjackal/tgstickers-blservice
    ports:
      - 10001:10000
    environment:
      - REDIS_URI=redis://redis:6379
      - JAVAMEM=85m
      - LOG4JCONF=log4jprod.xml
      - SENTRY_DSN=$SENTRY_DSN
      - SENTRY_SERVERNAME=$HOSTNAME
      - COMMANDS=dockerize -wait tcp://redis:6379
      - DATASTORE_APP_ID=$DATASTORE_APP_ID
      - LOGGING_LEVEL=INFO
    depends_on:
      - redis
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "5"

  redis:
    mem_limit: 20m
    restart: on-failure
    image: redis:alpine
    ports:
      - 6379:6379
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "5"