language: java
jdk:
- oraclejdk9
branches:
  only:
  - master
sudo: required
services:
- docker
addons:
  apt:
    packages:
    - python3
install:
- wget -O docker-compose https://github.com/docker/compose/releases/download/1.13.0/docker-compose-Linux-x86_64
  && chmod +x docker-compose
- echo -e '<toolchains>\n  <toolchain>\n    <type>jdk</type>\n    <provides>\n      <version>1.9</version>\n      <vendor>oracle</vendor>\n    </provides>\n    <configuration>\n      <jdkHome>/usr/lib/jvm/java-9-oracle</jdkHome>\n    </configuration>\n  </toolchain>\n</toolchains>\n' > ~/.m2/toolchains.xml
script: python3 etc/test/test.py
before_install:
- openssl aes-256-cbc -K $encrypted_6e59aab5d226_key -iv $encrypted_6e59aab5d226_iv
  -in deployment_key.enc -out /tmp/deployment_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deployment_key
- ssh-add /tmp/deployment_key
addons:
  ssh_known_hosts: 35.188.89.38
cache:
  directories:
  - $HOME/.m2
