version: "3"

services:
  inservice:
    image: tgstickers/inservice
    ports:
      - 8000:8080
    networks:
      - kafkanet
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
  
  outservice:
    image: tgstickers/outservice
    ports:
      - 8001:8080
    networks:
      - kafkanet
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
  
  blservice:
    image: tgstickers/blservice
    ports:
      - 8002:8080
    networks:
      - kafkanet
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
        
networks:
  kafkanet:
