version: "3"

services:
  inservice:
    image: ingvarjackal/tgstickers-inservice
    ports:
      - 8000:8080
    networks:
      - kafkanet
    deploy:
      resources:
        limits:
          memory: 150m
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
  
  outservice:
    image: ingvarjackal/tgstickers-outservice
    ports:
      - 8001:8080
    networks:
      - kafkanet
    deploy:
      resources:
        limits:
          memory: 150m
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
  
  blservice:
    image: ingvarjackal/tgstickers-blservice
    ports:
      - 8002:8080
    networks:
      - kafkanet
    deploy:
      resources:
        limits:
          memory: 150m
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
        
networks:
  kafkanet:
