version: "2"

services:
  inservice:
    mem_limit: 75m
    build: in_service/src/main/docker
    ports:
      - 18000:8080
    environment:
     - REDIS_URI=redis://redis:6379
     - JAVAMEM=70m
     - LOG4JCONF=log4jtest.xml
     - COMMANDS=dockerize -wait tcp://redis:6379
     - BOT_TOKEN=$BOT_TOKEN
    depends_on:
      - redis

  outservice:
    mem_limit: 75m
    build: out_service/src/main/docker
    environment:
      - REDIS_URI=redis://redis:6379
      - COMMANDS=dockerize -wait tcp://redis:6379
      - JAVAMEM=70m
      - LOG4JCONF=log4jtest.xml
      - BOT_TOKEN=$BOT_TOKEN
    depends_on:
      - redis

  blservice:
    mem_limit: 90m
    build: bl_service/src/main/docker
    environment:
      - REDIS_URI=redis://redis:6379
      - JAVAMEM=85m
      - LOG4JCONF=log4jtest.xml
      - COMMANDS=dockerize -wait tcp://datastore:8081 -wait tcp://redis:6379
      - DATASTORE_EMULATOR_HOST=datastore:8081
      - DATASTORE_APP_ID=tgstickers-228
    depends_on:
      - redis
      - datastore

  redis:
    mem_limit: 20m
    image: redis:alpine
    ports:
      - 6379:6379

  datastore:
    image: google/cloud-sdk:latest
    expose:
      - 8081
    command: gcloud beta emulators datastore start --project=tgstickers-228 --host-port datastore:8081 --no-store-on-disk
